---
title: "Mexico vs Global scores"
author: "Jamie Afflerbach"
date: "2/23/2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

```{r data}

data <- read_csv("data/OHI_final_formatted_scores_2017-11-22.csv") %>%
  filter(region_name %in% c("Global average", "Mexico"),    #filter for only the global and mexico scores
         dimension == "score",
         !str_detect(long_goal, "subgoal"), #remove all rows where subgoal is in the name
         !long_goal %in% c("Livelihoods", "Economies")) %>% 
  mutate(year = as.character(scenario), #forcing years to be characters so they aren't plotted as continuous values
         long_goal = ifelse(long_goal == "Index", "Overall", long_goal)) 

```

```{r plot, fig.width = 8, fig.height = 6}

ggplot(data, aes(x = long_goal, y = value, color = year, shape = region_name)) +
  geom_point(cex = 4) +
  ylab("SCORES") +
  xlab("") +
  theme_bw() +
  theme(axis.text.x = element_text(face="bold", size=10, angle=45, vjust = 1, hjust = 1, color = "white"),
        axis.title.y = element_text(face = "bold", color = "white"),
        axis.text.y = element_text(color = "white", size = 10, face = "bold"),
        legend.text = element_text(color = "white", face = "bold", size = 11),
        legend.title=element_blank(), 
        panel.background = element_rect(fill = "transparent"), # bg of the panel
        plot.background = element_rect(fill = "transparent"), # bg of the plot
        panel.grid.minor = element_blank(), # get rid of minor grid
        legend.background = element_rect(fill = "transparent")) + # get rid of legend bg
  scale_x_discrete(limits=c("Overall", "Artisanal opportunities", "Biodiversity", 
                            "Carbon storage", "Clean water", "Coastal protection", 
                            "Food provision", "Livelihoods & economies", "Natural products", 
                            "Sense of place", "Tourism & recreation")) +
  scale_color_brewer(name = "", palette = "Blues") +
  scale_y_continuous(breaks = seq(0, 100, 10))

ggsave("figs/mexico_global_scores.pdf", width = 8, height = 6)

```

Spanish version

```{r plot, fig.width = 8, fig.height = 6}

sp_data <- data %>%
  mutate(region_name = ifelse(region_name == "Global average", "Promedio global", "México")) %>%
  mutate(long_goal = case_when(
    long_goal == "Overall" ~ "General",
    long_goal == "Artisanal opportunities" ~ "Oportunidad de pesca artesenal",
    long_goal == "Biodiversity" ~ "Bioversidad",
    long_goal == "Carbon storage" ~ "Almacenamiento de carbono",
    long_goal == "Clean water" ~ "Aguas limpias",
    long_goal == "Coastal protection" ~ "Protección costera",
    long_goal == "Food provision" ~ "Provisión de alimentos",
    long_goal == "Livelihoods & economies" ~ "Subsistencia y economías",
    long_goal == "Natural products" ~ "Productos naturales",
    long_goal == "Sense of place" ~ "Identidad cultural",
    long_goal == "Tourism & recreation" ~ "Turismo y recreación"
  ))

ggplot(sp_data, aes(x = long_goal, y = value, color = year, shape = region_name)) +
  geom_point(cex = 4) +
  ylab("Valores de las metas") +
  xlab("") +
  theme_bw() +
  theme(axis.text.x = element_text(face="bold", size=10, angle=45, vjust = 1, hjust = 1, color = "white"),
        axis.title.y = element_text(face = "bold", color = "white"),
        axis.text.y = element_text(color = "white", size = 10, face = "bold"),
        legend.text = element_text(color = "white", face = "bold", size = 11),
        legend.title=element_blank(), 
        panel.background = element_rect(fill = "transparent"), # bg of the panel
        plot.background = element_rect(fill = "transparent"), # bg of the plot
        panel.grid.minor = element_blank(), # get rid of minor grid
        legend.background = element_rect(fill = "transparent")) + # get rid of legend bg
  scale_x_discrete(limits=c("General", "Oportunidad de pesca artesenal", "Bioversidad", 
                            "Almacenamiento de carbono", "Aguas limpias", "Protección costera", 
                            "Provisión de alimentos", "Subsistencia y economías", "Productos naturales", 
                            "Identidad cultural", "Turismo y recreación")) +
  scale_color_brewer(name = "", palette = "Blues") +
  scale_y_continuous(breaks = seq(0, 100, 10))

ggsave("figs/mexico_global_scores_spanish.pdf", width = 8, height = 6)

```


